### ISSUE TITLE
Investigate adding inband_mgmt to Day2 Ops section of AVD Workshop

### ISSUE THREAD

**Issue by mitchv85** [aristanetworks/avd-workshops#120]
This feature should be showcased during the AVD workshop. Render configuration, but do not push, as it will break the management connectivity to the switches in the ATD topology:

https://avd.sh/en/stable/docs/porting-guides/4.x.x.html?h=inband_mgmt#in-band-management-for-l2-switches

**Comment by JulioPDX** [comment]
Migrating to new site hosted on GCP. Issue will be closed for maintainers to address this in the new repository. Thank you
