### ISSUE TITLE
Move to AVD 4.5.0 for workshop

### ISSUE THREAD

**Issue by mitchv85** [aristanetworks/avd-workshops#121]
- Adjust this section of the AVD Lab guide to install AVD 4.5.0, and all requirements, into the lab environment:

https://aristanetworks.github.io/avd-workshops/avd-lab-guide/#step-1-prepare-lab-environment

- Run through AVD lab to make sure there are no issues

**Comment by mthiel117** [comment]
Fixes Issue #118
