### ISSUE TITLE
Suggesting to add a small section explaining the prod.yml

### ISSUE THREAD

**Issue by daniel1820815** [aristanetworks/avd-workshops#125]
Hi there! I was going through the CICD Basics workshop and I would like to suggest adding a small section explaining the prod.yml for GitHub Actions similar to the part about the dev.yml.

It could be before or after the following part in my opinion:

> At this point, this will kick off our second workflow (prod.yml) against the main branch. This workflow will build and deploy our updates with CVP.

Then it would be clearer (at least for me) how GitHub Actions triggers CVP and creates tasks there. After checking the prod.yml file it was clear but I thought it's missing in the workshop. Other than that great job!

**Comment by JulioPDX** [comment]
Apologies for the late reply and thank you for the feedback. The team will ramp back up and knockout these issues in the coming weeks. 👍🏾
