### ISSUE TITLE
Doc: Remove Create a GitHub personal access token

### ISSUE THREAD

**Issue by carlbuchmann** [aristanetworks/avd-workshops#127]
This is no longer required as the labs are now using a one-time token
https://aristanetworks.github.io/avd-workshops/git/#create-a-github-personal-access-token

**Comment by carlbuchmann** [comment]
Please assign @philippebureau

**Comment by JulioPDX** [comment]
@MitchV85 Any issues here? We've had instances where students think they need to create this as they go through the lab within the ATD

**Comment by mjbear** [comment]
@JulioPDX 

My two cents as a student, although there is a Note just before the token section it is easy to get sucked into the bold headings. :man_shrugging:  I would suggest additionally adding a note in the section itself so it's reinforced that step is not needed for the lab IDE.

Additionally I would suggest retaining the token write up, but making it a collapsed section. Thoughts?

Here's my take on it in PR #135

**Comment by mitchv85** [comment]
@JulioPDX and @carlbuchmann - No issues here. If the token is no longer necessary for the workshops, then let's remove the section about how to create one. We will leave the admonition in place that calls out the need to create a token if not using the ATD environment. 

Let's go ahead and remove

**Comment by JulioPDX** [comment]
This is fixed in a PR in flight. Thank you all for the comments

**Comment by mthiel117** [comment]
fixed #135
