### ISSUE TITLE
Doc: make it clearer on where/how to update ansible_ssh_pass

### ISSUE THREAD

**Issue by carlbuchmann** [aristanetworks/avd-workshops#128]
Make it clear that the user needs to update ansible_ssh_pass in the following group_var:
WORKSHOP_FABRIC.yml (~/project/labfiles/ci-workshops-fundamentals/ansible/inventory/group_vars/WORKSHOP_FABRIC.yml)

https://aristanetworks.github.io/avd-workshops/ansible/#variables

**Comment by JulioPDX** [comment]
We just ran into this yesterday as well. Great catch

**Comment by mjbear** [comment]
@carlbuchmann @JulioPDX 

I submitted PR #139 to add a reminder admonition regarding setting the `ansible_ssh_pass` in `WORKSHOP_FABRIC.yml`.

**Comment by mthiel117** [comment]
fixed #139
