### ISSUE TITLE
Updates to Workshop

### ISSUE THREAD

**Issue by JulioPDX** [aristanetworks/avd-workshops#129]
Seen under the Ansible components section 

![image](https://github.com/aristanetworks/avd-workshops/assets/34353177/dfc15d57-de29-4ae7-836a-3ea8d3e6cb1b)

- update output for correct ansible-core version
- Add note on main page to leverage with ATD or personal but needs additional requirements
- update official doc references to 4.5 (current build of workshops)
- Remove old lab credentials and replicate what students see
- Add ATD specific note
- Update ansible galaxy collection list output

**Comment by mjbear** [comment]
@JulioPDX - yes indeed, glad I saw this so I don't put in a PR for something you're already planning to fix. :-)

**Comment by JulioPDX** [comment]
Pending, additional update points will be update this week
