### ISSUE TITLE
jinja-yaml.md - clarify explanation of YAML lists

### ISSUE THREAD

**Issue by mjbear** [aristanetworks/avd-workshops#136]
The following sentence is a bit clunky.

Lists, which are sometimes also called sequences, are similar to arrays in development.
https://github.com/aristanetworks/avd-workshops/blob/main/workshops/jinja-yaml.md?plain=1#L172

In regard to the "in development" wording, was the message meant to be that lists in YAML are similar to arrays in other programming languages?

(I'm fine submitting a PR once this is sorted out.)
Maybe it could be written as:

Lists, sometimes called sequences, are similar to arrays in other programming languages.
**or**
Lists, sometimes called sequences, are similar to arrays in other programming languages and technologies.

**Comment by mjbear** [comment]
@JulioPDX 
Might you have any thoughts on this sentence?
https://github.com/aristanetworks/avd-workshops/blob/main/workshops/jinja-yaml.md?plain=1#L172

Thank you.

**Comment by JulioPDX** [comment]
@mjbear Thank you for the issue,  I'll create a duplicate in our new docs repo to make sure we can track it.
