### ISSUE TITLE
Docs: avd-lab-guide.md - simplify the expression used to set LABPASSPHRASE

### ISSUE THREAD

**Issue by mjbear** [aristanetworks/avd-workshops#148]
Hello Arista Engineering people,

Mr. T asked me to put in issues before I open up PRs. I fully intend to open up PRs once suggestions are agreed upon. :sunglasses: 

In both `avd-lab-guide.md` and `cicd-basics.md` there is an expression (piped shell commands) used to retrieve the `LABPASSPHRASE` from `config.yaml`. I have a suggestion that simplifies it greatly to exclusively an `awk` command.

Are you good with me submitting this as a PR?

Thank you!

**Comment by JulioPDX** [comment]
Oh yeah, that shortcut is not set in stone. Anything to simplify process is a good thing!

**Comment by mjbear** [comment]
Submitted PR #152

**Comment by JulioPDX** [comment]
Fixed in #152
