### ISSUE TITLE
Docs: avd-lab-guide.md - set LABPASSPHRASE in zsh config

### ISSUE THREAD

**Issue by mjbear** [aristanetworks/avd-workshops#149]
Hello Arista Engineering people,

On the heels of issue #148, I have a suggestion that the method for setting `LABPASSPHRASE`. For the students' benefit, it should still be explained early in the `avd-lab-guide.md`, but be made an (automatic) entry in the `zsh` config as a usability/life improvement when opening new shells. :grin: 

I'm game to include this in a PR (most likely along with #148 should that be blessed).

Thoughts?

Thank you!

**Comment by JulioPDX** [comment]
If you want to add this to the zsh file, that would have to be done under the ATD repo, within the [nested-release](https://github.com/aristanetworks/atd-public) branch. We leverage the ATD environment but this repository doesn't manage the ATDs.

**Comment by JulioPDX** [comment]
For example, within the code container [Dockerfile](https://github.com/aristanetworks/atd-public/blob/nested-release/nested-labvm/atd-docker/coder/Dockerfile)

**Comment by mjbear** [comment]
> For example, within the code container [Dockerfile](https://github.com/aristanetworks/atd-public/blob/nested-release/nested-labvm/atd-docker/coder/Dockerfile)

Understood, thank you.
I opened an [issue over on atd-public](https://github.com/aristanetworks/atd-public/issues/827).

Since this actual change would occur in `atd-public` if approved, I will be closing this issue.
