### ISSUE TITLE
Docs: avd-lab-guide.md - grammar and line number references

### ISSUE THREAD

**Issue by mjbear** [aristanetworks/avd-workshops#150]
Hello Arista Engineering people,

Along with #148 and #149...

There are two grammatical and content related items in avd-lab-guide.md I'd like to bring up for discussion.
Based on the outcome of our discussion I will submit a PR to cover the approved items. Thank you.

1. Change "Login to" to "Log into"
    - [Login to your switches to verify the current configs (show run) match the ones created in intended/configs folder.](https://github.com/aristanetworks/avd-workshops/blob/e16b7b80d29c3071b0755f7f3901a8dc5336d722/workshops/avd-lab-guide.md?plain=1#L141)

2. The line numbers no longer exactly correlate. Should the line number reference be updated or changed to a relative statement?
    - [Starting at line 64, add the following code block into `sites/site_1/group_vars/SITE1_FABRIC.yml`.](https://github.com/aristanetworks/avd-workshops/blob/e16b7b80d29c3071b0755f7f3901a8dc5336d722/workshops/avd-lab-guide.md?plain=1#L654)

3. Similar to item 2, the line number is no longer accurate.
    - [Make sure the indentation of `RACK3` is the same as `RACK2`, which can be found on line 52](https://github.com/aristanetworks/avd-workshops/blob/e16b7b80d29c3071b0755f7f3901a8dc5336d722/workshops/avd-lab-guide.md?plain=1#L670C5-L670C95)

**Comment by JulioPDX** [comment]
Oh wow, I love your appreciation for good grammar. Login, log into, log in. Please go ahead and submit a PR for all of these items. I messed up the line numbering when I added the mlag config portions for same subnet.

**Comment by mjbear** [comment]
My school grammar teachers left a mark on me, haha.

All good. If the line numbers continue to change we might consider referencing the line based on the relative position.

Examples:
- Below the section `- group: RACK2`
- in between the RACK2 section and Underlay Routing Protocol

**Comment by mjbear** [comment]
Submitted PR #152

**Comment by JulioPDX** [comment]
Fixed in #152
