### ISSUE TITLE
Add dark mode to icons

### ISSUE THREAD

**Issue by kpbush30** [aristanetworks/avd-workshops#161]
# Summary

Need to add some color or light/dark mode icons to improve readability of icons.

<img width="813" alt="Screenshot 2024-09-30 at 15 16 10" src="https://github.com/user-attachments/assets/3bc60014-04b2-4928-8686-e60b454dc691">

_Originally posted by @gmuloc in https://github.com/aristanetworks/avd-workshops/issues/159#issuecomment-2383165239_

**Comment by JulioPDX** [comment]
Will be updated in new docs repo
