### ISSUE TITLE
Add AVD global_vars plugin into AVD labs

### ISSUE THREAD

**Issue by mitchv85** [aristanetworks/avd-workshops#80]
No longer use include_vars. Instead we'll use the new AVD global_vars plugin for all global variables:

https://avd.arista.com/4.1/plugins/index.html?h=vars_pl#vars-plugins

**Comment by philippebureau** [comment]
I am taking this Issue

**Comment by philippebureau** [comment]
PR created
https://github.com/aristanetworks/avd-workshops/pull/95

**Comment by mitchv85** [comment]
fixed - #95 

Thanks again for taking this one @philippebureau
